In [11]:
#importing libraries to use
import pandas as pd
from bs4 import BeautifulSoup
import requests
import re
import matplotlib.pyplot as plt
import numpy as np

In [12]:
#connecting to url 
url = "https://en.wikipedia.org/wiki/List_of_most-polluted_cities_by_particulate_matter_concentration"

r = requests.get(url)

In [13]:
#using beautiful soup to read the webpage 
soup = BeautifulSoup(r.content, 'html5lib')

table = soup.findAll('table', attrs = {'class': 'wikitable sortable'}) #reading the table removes headers and text from page

In [14]:
#reading the text from the table
for row in table:
    print(row.text)

Position

Country

City/Town

Year

PM2.5

Temporal coverage

PM10

Temporal coverage

Database version (year)


1

India

Kanpur

2016

173

>75%

319

NA

2018


2

India

Faridabad

2016

172

>75%

316

NA

2018


3

India

Gaya

2016

149

50% -< 75%

275

NA

2018


4

India

Varanasi

2016

146

>75%

260

NA

2018


5

India

Patna

2016

144

>75%

266

NA

2018


6

India

Delhi

2016

143

>75%

292

NA

2018


7

India

Lucknow

2016

138

>75%

255

NA

2018


8

Cameroon

Bamenda

2012

132

NA

141

NA

2016


9

India

Agra

2016

131

>75%

194

NA

2018


10

India

Gurgaon

2016

120

50% -< 75%

124

NA

2018


11

India

Muzaffarpur

2016

120

>75%

221

NA

2018


12

Pakistan

Peshawar

2010

111

NA

540

NA

2016


13

Pakistan

Rawalpindi

2010

107

NA

448

NA

2016


14

India

Jaipur

2016

105

50% -< 75%

193

NA

2018


15

Uganda

Kampala

2013

104

NA

170

NA

2016


16

India

Patiala

2016

101

NA

184

NA

2018


17

India

Jodhpur

2016

98

>75%

180

NA

2018


18

Bangladesh

Narayangonj

2015

94

>75%

205

>75%

2018


19

China

Baoding

2016

93

NA

147

NA

2018


20

Qatar

Doha

2012

93

NA

168

NA

2016


21

Mongolia

Ulaanbaatar

2016

92

>75%

197

NA

2018


22

China

Ji'nan

2014

90

NA

192

NA

2018


23

China

Shijiazhuang

2015

89

NA

147

NA

2018


24

Pakistan

Karachi

2009

88

NA

290

NA

2016


25

China

Hengshui

2016

87

NA

143

NA

2018


26

China

Xingtai

2016

87

NA

186

NA

2018


27

China

Anyang

2016

86

NA

155

NA

2018


28

China

Liaocheng

2016

86

NA

151

NA

2018


29

China

Jiaozuo

2016

85

NA

142

NA

2018


30

Qatar

Al Wakrah

2012

85

NA

152

NA

2016


31

Bangladesh

Khulna

2015

84

50% -< 75%

94

>75%

2018


32

China

Xinxiang

2016

84

NA

144

NA

2018


33

India

Nagpur

2016

84

NA

86

NA

2018


34

China

Handan

2016

82

NA

175

NA

2018


35

China

Heze

2016

82

NA

143

NA

2018


36

China

Ji'ning

2015

82

NA

140

NA

2018


37

China

Xianyang

2016

82

NA

149

NA

2018


38

Bangladesh

Gazipur

2015

81

>75%

143

>75%

2018


39

China

Dezhou

2016

81

NA

141

NA

2018


40

China

Zaozhuang

2016

81

NA

141

NA

2018


41

Bangladesh

Barisal

2015

80

>75%

113

>75%

2018


42

China

Dongying

2015

79

NA

136

NA

2018


43

China

Luoyang

2016

79

NA

130

NA

2018


44

Kuwait

Al-Ahmadi

2015

79

>75%

138

>75%

2018


45

China

Shouguang

2014

78

NA

117

NA

2016


46

China

Zhengzhou

2016

78

NA

143

NA

2018


47

China

Luohe

2016

77

NA

130

NA

2018


48

China

Shangqiu

2016

77

NA

127

NA

2018


49

China

Weinan

2016

76

NA

139

NA

2018


50

China

Pingdingshan

2016

75

NA

125

NA

2018


51

Saudi Arabia

Yanbu

2017

75

>75%

116

>75%

2018


52

China

Linfen

2016

74

NA

158

NA

2018


53

China

Tangshan

2016

74

NA

127

NA

2018


54

China

Urumqi

2016

74

NA

115

NA

2018


55

India

Kolkata

2016

74

>75%

136

NA

2018


56

China

Beijing

2016

73

NA

92

NA

2018


57

China

Hebi

2016

73

NA

128

NA

2018


58

China

Jinan

2016

73

NA

141

NA

2018


59

China

Laiwu

2016

73

NA

127

NA

2018


60

China

Zigong

2016

73

NA

99

NA

2018


61

Saudi Arabia

Riyadh

2016

73

NA

251

NA

2018


62

China

Anshan

2015

72

NA

115

NA

2018


63

China

Kaifeng

2016

72

NA

122

NA

2018


64

China

Xi'an

2016

71

NA

137

NA

2018


65

China

Binzhou

2016

70

NA

123

NA

2018


66

China

Yangquan

2014

70

NA

105

NA

2016


67

China

Cangzhou

2016

69

NA

147

NA

2018


68

China

Puyang

2016

69

NA

137

NA

2018


69

China

Tianjin

2016

69

NA

103

NA

2018


70

China

Jiangyin

2014

68

NA

102

NA

2016


71

China

Weinan

2014

68

NA

102

NA

2016


72

China

Xuchang

2016

68

NA

122

NA

2018


73

China

Zhoukou

2016

68

NA

113

NA

2018


74

China

Zhumadian

2016

68

NA

120

NA

2018


75

Pakistan

Lahore

2010

68

NA

198

NA

2016


76

Chile

Comuna De Coyhaique

2016

67

NA

85

NA

2018


77

China

Changzhi

2014

67

NA

101

NA

2016


78

Cameroon

Bafoussam

2012

67

NA

105

NA

2016


79

Bangladesh

Chittagong

2015

66

50% -< 75%

91

>75%

2018


80

Bahrain

Hamad Town

2012

66

NA

318

NA

2016


81

China

Langfang

2016

66

NA

112

NA

2018


82

China

Sanmenxia

2016

66

NA

127

NA

2018


83

China

Taiyuan

2016

66

NA

125

NA

2018


84

Iran

Hamedan

2013

66

NA

149

NA

2018


85

Pakistan

Islamabad

2011

66

NA

217

NA

2016


86

Bosnia and Herzegovina

Tuzla

2010

65

NA

106

NA

2016


87

India

Ahmedabad

2015

65

50% -< 75%

120

NA

2018


88

Bahrain

Ma'ameer

2012

64

NA

257

NA

2016


89

Bosnia and Herzegovina

Lukavac

2016

64

>75%

84

NA

2018


90

Chile

Coyhaique

2014

64

NA

75

NA

2016


91

China

Jurong

2014

64

NA

97

NA

2016


92

China

Luzhou

2016

64

NA

87

NA

2018


93

China

Xiangyang

2016

64

NA

93

NA

2018


94

India

Mumbai

2016

64

>75%

104

NA

2018


95

Bahrain

Manama

2016

63

50% -< 75%

154

NA

2018


96

China

Chengdu

2016

63

NA

105

NA

2018


97

China

Leshan

2016

63

NA

93

NA

2018


98

China

Nanyang

2016

63

NA

119

NA

2018


99

China

Tai'an

2016

63

NA

112

NA

2018


100

China

Xining

2014

63

NA

120

NA

2018


101

China

Jincheng

2016

62

NA

111

NA

2018


102

China

Jinzhong

2016

62

NA

109

NA

2018


103

China

Yichang

2016

62

NA

97

NA

2018


104

Bangladesh

Sylhet

2015

61

>75%

111

>75%

2018


105

Iran

Qods

2016

61

NA

140

NA

2018


106

China

Ezhou

2016

60

NA

100

NA

2018


107

China

Fuyang

2014

60

NA

90

NA

2016


108

China

Jingzhou

2016

60

NA

100

NA

2018


109

China

Xuzhou

2016

60

NA

118

NA

2018


110

China

Zhangjiagang

2014

60

NA

91

NA

2016


111

India

Chandrapur

2016

60

>75%

109

NA

2018


112

South Africa

Hartebeespoort

2014

60

NA

119

NA

2016


113

China

Baoji

2016

59

NA

111

NA

2018


114

China

Chuzhou

2016

59

NA

77

NA

2018


115

China

Tongchuan

2016

59

NA

104

NA

2018


116

Bahrain

Nabih Saleh

2012

58

NA

244

NA

2016


117

China

Bozhou

2016

58

NA

83

NA

2018


118

China

Jingmen

2016

58

NA

99

NA

2018


119

China

Korla

2014

58

NA

87

NA

2016


120

China

Lin'an

2014

58

NA

87

NA

2016


121

China

Pingdu

2014

58

NA

88

NA

2016


122

China

Wafangdian

2014

58

NA

88

NA

2016


123

China

Xinyang

2016

58

NA

96

NA

2018


124

China

Yibin

2015

58

NA

82

NA

2018


125

China

Yiwu

2014

58

NA

88

NA

2016


126

China

Zhuji

2014

58

NA

88

NA

2016


127

Iran

Ahvaz

2016

58

NA

132

NA

2018


128

Saudi Arabia

Jubail

2016

58

>75%

129

>75%

2018


129

Bangladesh

Dhaka

2016

57

>75%

104

NA

2018


130

China

Hefei

2016

57

NA

83

NA

2018


131

China

Huangshi

2016

57

NA

89

NA

2018


132

China

Maanshan

2014

57

NA

87

NA

2016


133

China

Nanchong

2014

57

NA

86

NA

2016


134

China

Wuhan

2016

57

NA

92

NA

2018


135

China

Changde

2016

56

NA

80

NA

2018


136

China

Dazhou

2016

56

NA

86

NA

2018


137

China

Huainan

2016

56

NA

85

NA

2018


138

China

Laixi

2014

56

NA

84

NA

2016


139

China

Laizhou

2014

56

NA

84

NA

2016


140

China

Linyi

2014

56

NA

84

NA

2016


141

China

Suizhou

2016

56

NA

88

NA

2018


142

China

Suqian

2016

56

NA

120

NA

2018


143

China

Wujiang

2014

56

NA

85

NA

2016


144

China

Xinzhou

2016

56

NA

103

NA

2018


145

Iran

Genaveh

2016

56

NA

129

NA

2018


146

Saudi Arabia

Dammam

2016

56

NA

161

NA

2018


147

China

Deyang

2016

55

NA

91

NA

2018


148

China

Jinzhou

2016

55

NA

81

NA

2018


149

China

Rizhao

2016

55

NA

101

NA

2018


150

China

Taian

2014

55

NA

83

NA

2016


151

China

Yinchuan

2016

55

NA

117

NA

2018


152

Ghana

Accra

2016

55

NA

112

NA

2018


153

India

Panchkula

2016

55

>75%

101

NA

2018


154

Iran

Asaluyeh

2016

55

NA

126

NA

2018


155

China

Anqing

2016

54

NA

71

NA

2018


156

China

Chongqing

2016

54

NA

77

NA

2018


157

China

Jining

2014

54

NA

81

NA

2016


158

China

Lanzhou

2016

54

NA

132

NA

2018


159

China

Neijiang

2016

54

NA

76

NA

2018


160

China

Shaoyang

2016

54

NA

77

NA

2018


161

China

Shenyang

2016

54

NA

94

NA

2018


162

China

Taicang

2014

54

NA

82

NA

2016


163

China

Yixing

2014

54

NA

81

NA

2016


164

China

Zhaoyuan

2014

54

NA

82

NA

2016


165

China

Zibo

2014

54

NA

82

NA

2016


166

China

Changsha

2016

53

NA

73

NA

2018


167

China

Huai'an

2016

53

NA

92

NA

2018


168

China

Wuhu

2016

53

NA

75

NA

2018


169

China

Wuxi

2016

53

NA

82

NA

2018


170

China

Harbin

2016

52

NA

74

NA

2018


171

China

Hengyang

2016

52

NA

76

NA

2018


172

China

Jiaonan

2014

52

NA

79

NA

2016


173

China

Jiaozhou

2014

52

NA

79

NA

2016


174

China

Liyang

2014

52

NA

78

NA

2016


175

China

Haimen

2014

51

NA

77

NA

2016


176

China

Huanggang

2016

51

NA

75

NA

2018


177

China

Jimo

2014

51

NA

77

NA

2016


178

China

Shiyan

2016

51

NA

81

NA

2018


179

China

Taizhou, Jiangsu

2016

51

NA

87

NA

2018


180

China

Tongling

2016

51

NA

78

NA

2018


181

China

Xiangtan

2016

51

NA

85

NA

2018


182

China

Xuancheng

2016

51

NA

68

NA

2018


183

China

Yangzhou

2016

51

NA

87

NA

2018


184

China

Zhuzhou

2016

51

NA

83

NA

2018


185

Kuwait

Saad Al-Abdullah

2016

51

50% -< 75%

63

>75%

2018


186

China

Baishan

2016

50

NA

81

NA

2018


187

China

Jiujiang

2016

50

NA

74

NA

2018


188

China

Zhenjiang

2016

50

NA

80

NA

2018


189

India

Pune

2016

50

>75%

89

NA

2018


190

Iran

Zabol

2016

50

NA

115

NA

2018


191

Chile

Padre Las Casas

2016

49

NA

64

NA

2018


192

China

Changshu

2014

49

NA

74

NA

2016


193

China

Changzhou

2016

49

NA

81

NA

2018


194

China

Hangzhou

2016

49

NA

105

NA

2018


195

China

Ma'anshan

2016

49

NA

75

NA

2018


196

China

Mianyang

2016

49

NA

78

NA

2018


197

China

Weifang

2014

49

NA

73

NA

2016


198

China

Xi'ning

2016

49

NA

113

NA

2018


199

China

Yueyang

2016

49

NA

72

NA

2018


200

China

Ziyang

2016

49

NA

95

NA

2018


201

Cameroon

Yaounde

2012

49

NA

65

NA

2016


202

India

Chennai

2016

49

>75%

80

NA

2018


203

Nepal

Kathmandu

2013

49

NA

88

NA

2016


204

China

Baicheng

2016

48

NA

75

NA

2018


205

China

Enshi

2016

48

NA

69

NA

2018


206

China

Jintan

2014

48

NA

72

NA

2016


207

China

Nanjing

2016

48

NA

85

NA

2018


208

China

Rushan

2014

48

NA

72

NA

2016


209

China

Tieling

2016

48

NA

83

NA

2018


210

China

Wuzhong

2016

48

NA

98

NA

2018


211

China

Xianning

2016

48

NA

77

NA

2018


212

China

Yan'an

2014

48

NA

73

NA

2016


213

China

Zhangjiajie

2016

48

NA

72

NA

2018


214

Vietnam

Hanoi

2016

48

>75%

102

NA

2018


215

Bangladesh

Rajshahi

2015

47

>75%

86

50% -< 75%

2018


216

China

Baotou

2016

47

NA

105

NA

2018


217

China

Guilin

2016

47

NA

64

NA

2018


218

China

Huludao

2016

47

NA

87

NA

2018


219

China

Huzhou

2016

47

NA

100

NA

2018


220

China

Liaoyang

2016

47

NA

83

NA

2018


221

China

Shizuishan

2016

47

NA

114

NA

2018


222

China

Zhangqiu

2014

47

NA

71

NA

2016


223

China

Changchun

2016

46

NA

78

NA

2018


224

China

Guang'an

2016

46

NA

78

NA

2018


225

China

Haidong

2016

46

NA

114

NA

2018


226

China

Jinhua

2016

46

NA

98

NA

2018


227

China

Kunshan

2014

46

NA

69

NA

2016


228

China

Lianyungang

2016

46

NA

87

NA

2018


229

China

Liaoyuan

2016

46

NA

63

NA

2018


230

China

Loudi

2016

46

NA

71

NA

2018


231

China

Lu'an

2016

46

NA

73

NA

2018


232

China

Nantong

2016

46

NA

70

NA

2018


233

China

Penglai

2014

46

NA

69

NA

2016


234

China

Qinhuangdao

2016

46

NA

87

NA

2018


235

China

Siping

2016

46

NA

77

NA

2018


236

China

Suzhou

2016

46

NA

72

NA

2018


237

China

Wendeng

2014

46

NA

69

NA

2016


238

China

Wuhai

2016

46

NA

111

NA

2018


239

India

Bangalore

2016

46

>75%

96

50% -< 75%

2018


240

Iran

Baghershahr

2016

46

NA

105

NA

2018


241

Iran

Bushehr

2016

46

NA

105

NA

2018


242

Philippines

Quezon City

2016

46

NA

98

NA

2018


243

China

Benxi

2016

45

NA

74

NA

2018


244

China

Daqing

2015

45

NA

62

NA

2018


245

China

Ganzhou

2016

45

NA

68

NA

2018


246

China

Huangnan

2016

45

NA

86

NA

2018


247

China

Qingdao

2016

45

NA

85

NA

2018


248

China

Shanghai

2016

45

NA

59

NA

2018


249

China

Shaoxing

2016

45

NA

68

NA

2018


250

China

Xiaogan

2016

45

NA

78

NA

2018


251

China

Yongzhou

2016

45

NA

70

NA

2018


252

Indonesia

Jakarta

2016

45

>75%

82

NA

2018


253

Philippines

Navotas City

2016

45

NA

96

NA

2018


254

Bahrain

Ras Hayan

2012

44

NA

250

NA

2016


255

Chile

Osorno

2016

44

NA

56

NA

2018


256

China

Fushun

2016

44

NA

78

NA

2018


257

China

Jiaxing

2016

44

NA

94

NA

2018


258

China

Liuzhou

2016

44

NA

66

NA

2018


259

China

Suining

2016

44

NA

68

NA

2018


260

China

Xiangxi

2016

44

NA

78

NA

2018


261

China

Yingkou

2016

44

NA

73

NA

2018


262

China

Yiyang

2016

44

NA

82

NA

2018


263

China

Zunyi

2016

44

NA

69

NA

2018


264

India

Hyderabad

2016

44

>75%

84

NA

2018


265

Iran

Dehloran

2016

44

NA

100

NA

2018


266

Iran

Mehran

2016

44

NA

102

NA

2018


267

China

Nanchang

2016

43

NA

92

NA

2018


268

China

Quzhou

2016

43

NA

92

NA

2018


269

China

Taizhou

2014

43

NA

71

NA

2018


270

China

Yancheng

2016

43

NA

92

NA

2018


271

China

Dandong

2016

42

NA

71

NA

2018


272

China

Datong

2014

42

NA

63

NA

2016


273

China

Huaihua

2016

42

NA

79

NA

2018


274

China

Jilin

2016

42

NA

69

NA

2018


275

China

Tianshui

2016

42

NA

80

NA

2018


276

China

Tonghua

2016

42

NA

76

NA

2018


277

China

Ya'an

2016

42

NA

68

NA

2018


278

Iran

Kangan

2016

42

NA

96

NA

2018


279

Vietnam

Ho Chi Minh City

2016

42

>75%

90

NA

2018


280

Bahrain

Hidd

2012

41

NA

178

NA

2016


281

Chile

Valdivia

2016

41

NA

67

NA

2018


282

China

Chenzhou

2016

41

NA

70

NA

2018


283

China

Hohhot

2016

41

NA

88

NA

2018


284

China

Pingliang

2016

41

NA

80

NA

2018


285

China

Shangrao

2016

41

NA

70

NA

2018


286

China

Yingtan

2016

41

NA

59

NA

2018


287

Colombia

La Estrella

2014

41

NA

47

NA

2016


288

Guatemala

Guatemala

2013

41

NA

56

NA

2016


289

Croatia

Slavonski Brod

2016

41

>75%

63

NA

2018


290

India

Navi Mumbai

2016

41

NA

67

NA

2018


291

India

Udaipur

2016

41

NA

98

NA

2018


292

South Africa

Johannesburg

2011

41

NA

85

NA

2016


293

China

Chengde

2016

40

NA

81

NA

2018


294

China

Panjin

2016

40

NA

67

NA

2018


295

India

Guwahati

2016

40

NA

81

NA

2018


296

North Macedonia

Skopje

2016

40

>75%

69

>75%

2018


297

China

Baiyin

2016

39

NA

95

NA

2018


298

China

Dalian

2016

39

NA

67

NA

2018


299

China

Jieyang

2016

39

NA

60

NA

2018


300

China

Liupanshui

2016

39

NA

68

NA

2018


301

China

Ningbo

2016

39

NA

62

NA

2018


302

China

Shangluo

2016

39

NA

72

NA

2018


303

China

Wuwei

2016

39

NA

97

NA

2018


304

China

Yantai

2016

39

NA

76

NA

2018


305

China

Zhaoyang

2016

39

NA

69

NA

2018


306

India

Solapur

2016

39

>75%

71

NA

2018


307

Iran

shahinshahr

2016

39

NA

89

NA

2018


308

Peru

Lima

2016

39

50% -< 75%

58

>75%

2018


309

Turkey

Amasya

2016

39

>75%

57

>75%

2018


310

China

Foshan

2016

38

NA

55

NA

2018


311

China

Gannan

2016

38

NA

70

NA

2018


312

China

Guigang

2016

38

NA

55

NA

2018


313

China

Rongcheng[disambiguation needed]

2014

38

NA

57

NA

2016


314

China

Wenzhou

2016

38

NA

81

NA

2018


315

China

Zhangye

2016

38

NA

90

NA

2018


316

India

Jabalpur

2016

38

NA

79

NA

2018


317

Iran

Shahre Ghods

2016

38

NA

87

NA

2018


318

Iran

Shahryar

2016

38

NA

87

NA

2018


319

China

Chifeng

2016

37

NA

76

NA

2018


320

China

Guiyang

2016

37

NA

63

NA

2018


321

China

Guoluo

2016

37

NA

72

NA

2018


322

China

Mudanjiang

2016

37

NA

68

NA

2018


323

China

Qinzhou

2016

37

NA

79

NA

2018


324

China

Zhaoqing

2016

37

NA

55

NA

2018


325

Iran

Lavan Island

2016

37

NA

85

NA

2018


326

Iran

Sari

2012

37

NA

90

NA

2016


327

Madagascar

Antananarivo

2008

37

NA

60

NA

2016


328

China

Dingxi

2016

36

NA

75

NA

2018


329

China

Guangzhou

2016

36

NA

56

NA

2018


330

China

Nanning

2016

36

NA

62

NA

2018


331

China

Qingyuan

2016

36

NA

52

NA

2018


332

China

Qiqihar

2016

36

NA

61

NA

2018


333

China

Taizhou, Zhejiang

2016

36

NA

77

NA

2018


334

Colombia

Medellin

2015

36

>75%

60

>75%

2018


335

Iran

Varamin

2016

36

NA

83

NA

2018


336

Iran

Yazd

2016

36

NA

83

NA

2018


337

Mexico

Monterrey

2011

36

NA

86

NA

2016


338

Pakistan

Faisalabad

2013

36

>75%

148

>75%

2018


339

Chile

El Bosque, Chile

2016

35

NA

67

NA

2018


340

Chile

Temuco

2016

35

NA

52

NA

2018


341

China

Dongguan

2016

35

NA

49

NA

2018


342

China

Songyuan

2016

35

NA

69

NA

2018


343

China

Weihai

2016

35

NA

63

NA

2018


344

Cuba

La Habana

2015

35

50% -< 75%

75

NA

2018


345

Guatemala

Guatemala City

2014

35

NA

47

NA

2018


346

India

Trivendrum

2016

35

NA

48

NA

2018


347

Iran

Ghom

2016

35

NA

81

NA

2018


348

China

Hechi

2016

34

NA

55

NA

2018


349

China

Jiangmen

2016

34

NA

55

NA

2018


350

China

Nantou

2014

34

NA

51

NA

2016


351

China

Shuangyashan

2016

34

NA

55

NA

2018


352

China

Yunfu

2016

34

NA

51

NA

2018


353

India

Vizag

2016

34

NA

76

NA

2018


354

Iran

Ilam, Iran

2016

34

NA

79

NA

2018


355

Philippines

Malabon

2015

34

NA

73

NA

2018


356

Philippines

Pasig

2016

34

NA

73

NA

2018


357

South Africa

Vereeniging

2014

34

NA

58

NA

2016


358

Chile

Cerro Navia

2016

33

NA

62

NA

2018


359

Chile

Los Ángeles

2016

33

NA

57

NA

2018


360

China

Chaozhou

2016

33

NA

51

NA

2018


361

China

Jiayuguan

2016

33

NA

98

NA

2018


362

China

Lishui

2016

33

NA

70

NA

2018


363

China

Shaoguan

2016

33

NA

51

NA

2018


364

China

Zhangzhou

2016

33

NA

65

NA

2018


365

Indonesia

Bandung

2014

33

NA

59

NA

2016


366

India

Tezpur

2016

33

NA

52

NA

2018


367

Iran

Khorramabad

2016

33

NA

75

NA

2018


368

Iran

Pakdasht

2016

33

NA

75

NA

2018


369

Lebanon

Zahle

2014

33

NA

40

NA

2016


370

Mexico

Toluca

2011

33

NA

80

NA

2016


371

Poland

Godów

2016

33

>75%

43

>75%

2018


372

Poland

Pleszew

2016

33

>75%

38

>75%

2018


373

Chile

Linares

2016

32

NA

65

NA

2018


374

Chile

Pudahuel

2016

32

NA

69

NA

2018


375

China

Changhua

2014

32

NA

48

NA

2016


376

China

Haibei

2016

32

NA

76

NA

2018


377

China

Heyuan

2016

32

NA

46

NA

2018


378

China

Jinchang

2016

32

NA

104

NA

2018


379

Taiwan

Kinmen

2014

32

NA

48

NA

2016


380

China

Panzhihua

2016

32

NA

65

NA

2018


381

China

Qujing

2014

32

NA

48

NA

2016


382

China

Zhangjiakou

2016

32

NA

68

NA

2018


383

Czech Republic

Dolni Lutyne

2016

32

>75%

40

>75%

2018


384

Iran

Abadan

2016

32

NA

74

NA

2018


385

Iran


In [32]:
#creating a list 
list_rows = []
for r in row:
    cells = row.find_all('td')
    str_cells = str(cells)
    clean = re.compile('<.*?>')
    clean2 = (re.sub(clean, '', str_cells))
    list_rows.append(clean2)

df = pd.DataFrame(list_rows)

df.head(10)

                                                   0
0  [1\n, India\n, Kanpur\n, 2016\n, 173\n, &gt;75...
1  [1\n, India\n, Kanpur\n, 2016\n, 173\n, &gt;75...

In [16]:
df1 = df[0].str.split(',', expand=True)
df1.head(10)

,0,1,2,3,4,5,6,7,8,9,...,4494,4495,4496,4497,4498,4499,4500,4501,4502,4503
0,[1\n,India\n,Kanpur\n,2016\n,173\n,&gt;75%\n,319\n,NA\n,2018\n,2\n,...,2018\n,500\n,Turkey\n,Sivas\n,2016\n,27\n,&gt;75%\n,56\n,&gt;75%\n,2018\n]
1,[1\n,India\n,Kanpur\n,2016\n,173\n,&gt;75%\n,319\n,NA\n,2018\n,2\n,...,2018\n,500\n,Turkey\n,Sivas\n,2016\n,27\n,&gt;75%\n,56\n,&gt;75%\n,2018\n]

In [17]:
df1[0] = df1[0].str.strip('[]')
df1.head(10)

,0,1,2,3,4,5,6,7,8,9,...,4494,4495,4496,4497,4498,4499,4500,4501,4502,4503
0,1\n,India\n,Kanpur\n,2016\n,173\n,&gt;75%\n,319\n,NA\n,2018\n,2\n,...,2018\n,500\n,Turkey\n,Sivas\n,2016\n,27\n,&gt;75%\n,56\n,&gt;75%\n,2018\n]
1,1\n,India\n,Kanpur\n,2016\n,173\n,&gt;75%\n,319\n,NA\n,2018\n,2\n,...,2018\n,500\n,Turkey\n,Sivas\n,2016\n,27\n,&gt;75%\n,56\n,&gt;75%\n,2018\n]

In [18]:
col_labels = soup.find_all('th')

all_header = []
col_str = str(col_labels)
cleantext2 = BeautifulSoup(col_str, "lxml").get_text()
all_header.append(cleantext2)
print(all_header)

['[Position\n, Country\n, City/Town\n, Year\n, PM2.5\n, Temporal coverage\n, PM10\n, Temporal coverage\n, Database version (year)\n]']

In [19]:
df2 = pd.DataFrame(all_header)
df2.head()

                                                   0
0  [Position\n, Country\n, City/Town\n, Year\n, P...

In [20]:
df3 = df2[0].str.split(',', expand=True)
df3.head()

,0,1,2,3,4,5,6,7,8
0,[Position\n,Country\n,City/Town\n,Year\n,PM2.5\n,Temporal coverage\n,PM10\n,Temporal coverage\n,Database version (year)\n]

In [21]:
frames = [df3, df1]
df4 = pd.concat(frames)
df4.head(10)

,0,1,2,3,4,5,6,7,8,9,...,4494,4495,4496,4497,4498,4499,4500,4501,4502,4503
0,[Position\n,Country\n,City/Town\n,Year\n,PM2.5\n,Temporal coverage\n,PM10\n,Temporal coverage\n,Database version (year)\n],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,1\n,India\n,Kanpur\n,2016\n,173\n,&gt;75%\n,319\n,NA\n,2018\n,2\n,...,2018\n,500\n,Turkey\n,Sivas\n,2016\n,27\n,&gt;75%\n,56\n,&gt;75%\n,2018\n]
1,1\n,India\n,Kanpur\n,2016\n,173\n,&gt;75%\n,319\n,NA\n,2018\n,2\n,...,2018\n,500\n,Turkey\n,Sivas\n,2016\n,27\n,&gt;75%\n,56\n,&gt;75%\n,2018\n]

In [22]:
df5 = df4.rename(columns=df4.iloc[0])
df5.head()

,[Position\n,Country\n,City/Town\n,Year\n,PM2.5\n,Temporal coverage\n,PM10\n,Temporal coverage\n,Database version (year)\n],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,[Position\n,Country\n,City/Town\n,Year\n,PM2.5\n,Temporal coverage\n,PM10\n,Temporal coverage\n,Database version (year)\n],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,1\n,India\n,Kanpur\n,2016\n,173\n,&gt;75%\n,319\n,NA\n,2018\n,2\n,...,2018\n,500\n,Turkey\n,Sivas\n,2016\n,27\n,&gt;75%\n,56\n,&gt;75%\n,2018\n]
1,1\n,India\n,Kanpur\n,2016\n,173\n,&gt;75%\n,319\n,NA\n,2018\n,2\n,...,2018\n,500\n,Turkey\n,Sivas\n,2016\n,27\n,&gt;75%\n,56\n,&gt;75%\n,2018\n]

In [23]:
#Since removing NA will remove most of the columns I am filling in with 0 instead
df6 = df5.fillna(0)
df6

,[Position\n,Country\n,City/Town\n,Year\n,PM2.5\n,Temporal coverage\n,PM10\n,Temporal coverage\n,Database version (year)\n],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,[Position\n,Country\n,City/Town\n,Year\n,PM2.5\n,Temporal coverage\n,PM10\n,Temporal coverage\n,Database version (year)\n],0,...,0,0,0,0,0,0,0,0,0,0
0,1\n,India\n,Kanpur\n,2016\n,173\n,&gt;75%\n,319\n,NA\n,2018\n,2\n,...,2018\n,500\n,Turkey\n,Sivas\n,2016\n,27\n,&gt;75%\n,56\n,&gt;75%\n,2018\n]
1,1\n,India\n,Kanpur\n,2016\n,173\n,&gt;75%\n,319\n,NA\n,2018\n,2\n,...,2018\n,500\n,Turkey\n,Sivas\n,2016\n,27\n,&gt;75%\n,56\n,&gt;75%\n,2018\n]

In [24]:
#removing top empty row
df7 = df6.drop(df6.index[0])
df7.head(10)

,[Position\n,Country\n,City/Town\n,Year\n,PM2.5\n,Temporal coverage\n,PM10\n,Temporal coverage\n,Database version (year)\n],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1\n,India\n,Kanpur\n,2016\n,173\n,&gt;75%\n,319\n,NA\n,2018\n,2\n,...,2018\n,500\n,Turkey\n,Sivas\n,2016\n,27\n,&gt;75%\n,56\n,&gt;75%\n,2018\n]

In [25]:
#looking for duplicates
df7.duplicated()

1    False
dtype: bool

In [26]:
#removing any duplicates
df7.drop_duplicates()

,[Position\n,Country\n,City/Town\n,Year\n,PM2.5\n,Temporal coverage\n,PM10\n,Temporal coverage\n,Database version (year)\n],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1\n,India\n,Kanpur\n,2016\n,173\n,&gt;75%\n,319\n,NA\n,2018\n,2\n,...,2018\n,500\n,Turkey\n,Sivas\n,2016\n,27\n,&gt;75%\n,56\n,&gt;75%\n,2018\n]

In [28]:
df7.to_csv(r'C:\Users\etc\OneDrive\DSC 540\Final Project\pollutedcities_pm.csv', index=False)